name: First Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src
   
    steps:
      - name: print Hello World
        run: echo "Hello World"
    
